// File generated by RouteSense migration engine for Firebase configuration.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for RouteSense.
///
/// Example usage:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATX8azNtb3Z8H4JP7Xkgym-HbtUIK1WvQ',
    appId: '1:817062690867:web:5287578fe46a3484186346',
    messagingSenderId: '817062690867',
    projectId: 'steadfast-skyline-v8kj5',
    authDomain: 'steadfast-skyline-v8kj5.firebaseapp.com',
    storageBucket: 'steadfast-skyline-v8kj5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATX8azNtb3Z8H4JP7Xkgym-HbtUIK1WvQ',
    appId: '1:817062690867:android:5287578fe46a3484186346',
    messagingSenderId: '817062690867',
    projectId: 'steadfast-skyline-v8kj5',
    storageBucket: 'steadfast-skyline-v8kj5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATX8azNtb3Z8H4JP7Xkgym-HbtUIK1WvQ',
    appId: '1:817062690867:ios:5287578fe46a3484186346',
    messagingSenderId: '817062690867',
    projectId: 'steadfast-skyline-v8kj5',
    storageBucket: 'steadfast-skyline-v8kj5.firebasestorage.app',
    iosBundleId: 'com.routesense.fleet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATX8azNtb3Z8H4JP7Xkgym-HbtUIK1WvQ',
    appId: '1:817062690867:ios:5287578fe46a3484186346',
    messagingSenderId: '817062690867',
    projectId: 'steadfast-skyline-v8kj5',
    storageBucket: 'steadfast-skyline-v8kj5.firebasestorage.app',
    iosBundleId: 'com.routesense.fleet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATX8azNtb3Z8H4JP7Xkgym-HbtUIK1WvQ',
    appId: '1:817062690867:web:5287578fe46a3484186346',
    messagingSenderId: '817062690867',
    projectId: 'steadfast-skyline-v8kj5',
    authDomain: 'steadfast-skyline-v8kj5.firebaseapp.com',
    storageBucket: 'steadfast-skyline-v8kj5.firebasestorage.app',
  );
}
