import '../../models/user_model.dart';
import '../../models/route_model.dart';
import '../../models/bus_model.dart';
import '../../models/trip_model.dart';
import '../../models/ticket_model.dart';
import '../../models/incident_model.dart';
import '../../models/notification_model.dart';
import '../../models/recurring_issue_model.dart';

class InitialData {
  static final List<UserModel> users = [
    UserModel(
      uid: 'user_conductor_1',
      name: 'Anita Deshmukh',
      email: 'anita.conductor@routesense.city',
      phone: '+91 98765 43210',
      role: 'conductor',
      routeAssigned: 'route_101',
      busAssigned: 'bus_MH12_AB1234',
      createdAt: '2026-01-15T08:00:00Z',
      employeeId: 'CND-4092',
      shiftStatus: 'on_duty',
    ),
    UserModel(
      uid: 'user_driver_1',
      name: 'Rajesh Patil',
      email: 'rajesh.driver@routesense.city',
      phone: '+91 98765 43211',
      role: 'driver',
      routeAssigned: 'route_101',
      busAssigned: 'bus_MH12_AB1234',
      createdAt: '2026-01-10T07:30:00Z',
      employeeId: 'DRV-1088',
      shiftStatus: 'on_duty',
    ),
    UserModel(
      uid: 'user_ops_1',
      name: 'Siddharth Varma',
      email: 'siddharth.ops@routesense.city',
      phone: '+91 98765 43212',
      role: 'operations_manager',
      createdAt: '2026-01-01T09:00:00Z',
      employeeId: 'OPS-001',
      shiftStatus: 'on_duty',
    ),
    UserModel(
      uid: 'user_passenger_1',
      name: 'Pooja Kulkarni',
      email: 'pooja.passenger@gmail.com',
      phone: '+91 98765 43213',
      role: 'passenger',
      createdAt: '2026-02-01T10:00:00Z',
      shiftStatus: 'on_duty',
    ),
  ];

  static final List<RouteModel> routes = [
    RouteModel(
      routeId: 'route_101',
      routeName: 'Swargate to Hinjawadi IT Park',
      routeNumber: '101-EXP',
      startPoint: 'Swargate Terminal',
      endPoint: 'Hinjawadi Phase 3 Circle',
      farePerStop: 5.0,
      baseFare: 10.0,
      activeFlag: true,
      totalDistanceKm: 24.5,
      avgDurationMin: 65,
      frequencyMin: 12,
      activeBusesCount: 3,
      createdAt: '2026-01-01T00:00:00Z',
      scheduledStops: [
        StopModel(stopId: 's1', name: 'Swargate Terminal', order: 0, etaMinutes: 0, lat: 18.5018, lng: 73.8580, isMajor: true),
        StopModel(stopId: 's2', name: 'Deccan Gymkhana', order: 1, etaMinutes: 10, lat: 18.5175, lng: 73.8415, isMajor: true),
        StopModel(stopId: 's3', name: 'Shivajinagar Bus Station', order: 2, etaMinutes: 20, lat: 18.5308, lng: 73.8474, isMajor: true),
        StopModel(stopId: 's4', name: 'Pune University Circle', order: 3, etaMinutes: 32, lat: 18.5529, lng: 73.8248, isMajor: true),
        StopModel(stopId: 's5', name: 'Aundh Gaon', order: 4, etaMinutes: 42, lat: 18.5601, lng: 73.8066, isMajor: false),
        StopModel(stopId: 's6', name: 'Wakad Bridge', order: 5, etaMinutes: 52, lat: 18.5987, lng: 73.7634, isMajor: true),
        StopModel(stopId: 's7', name: 'Hinjawadi Shivaji Chowk', order: 6, etaMinutes: 58, lat: 18.5913, lng: 73.7389, isMajor: true),
        StopModel(stopId: 's8', name: 'Hinjawadi Phase 3 Circle', order: 7, etaMinutes: 65, lat: 18.5833, lng: 73.6980, isMajor: true),
      ],
    ),
    RouteModel(
      routeId: 'route_202',
      routeName: 'Pune Station to Hadapsar Gadital',
      routeNumber: '202',
      startPoint: 'Pune Railway Station',
      endPoint: 'Hadapsar Gadital',
      farePerStop: 5.0,
      baseFare: 10.0,
      activeFlag: true,
      totalDistanceKm: 14.2,
      avgDurationMin: 40,
      frequencyMin: 15,
      activeBusesCount: 2,
      createdAt: '2026-01-01T00:00:00Z',
      scheduledStops: [
        StopModel(stopId: 's201', name: 'Pune Railway Station', order: 0, etaMinutes: 0, lat: 18.5284, lng: 73.8744, isMajor: true),
        StopModel(stopId: 's202', name: 'Ruby Hall Clinic', order: 1, etaMinutes: 8, lat: 18.5327, lng: 73.8812, isMajor: false),
        StopModel(stopId: 's203', name: 'Bund Garden', order: 2, etaMinutes: 14, lat: 18.5369, lng: 73.8860, isMajor: false),
        StopModel(stopId: 's204', name: 'Yerwada Post Office', order: 3, etaMinutes: 22, lat: 18.5529, lng: 73.8887, isMajor: true),
        StopModel(stopId: 's205', name: 'Kalyani Nagar Bridge', order: 4, etaMinutes: 30, lat: 18.5463, lng: 73.9038, isMajor: false),
        StopModel(stopId: 's206', name: 'Magarpatta South Gate', order: 5, etaMinutes: 35, lat: 18.5134, lng: 73.9281, isMajor: true),
        StopModel(stopId: 's207', name: 'Hadapsar Gadital', order: 6, etaMinutes: 40, lat: 18.5034, lng: 73.9312, isMajor: true),
      ],
    ),
    RouteModel(
      routeId: 'route_303',
      routeName: 'Katraj to Nigdi Pradhikaran',
      routeNumber: '303-BRT',
      startPoint: 'Katraj Wonder City',
      endPoint: 'Nigdi Bhakti Shakti',
      farePerStop: 5.0,
      baseFare: 15.0,
      activeFlag: true,
      totalDistanceKm: 28.0,
      avgDurationMin: 75,
      frequencyMin: 10,
      activeBusesCount: 2,
      createdAt: '2026-01-01T00:00:00Z',
      scheduledStops: [
        StopModel(stopId: 's301', name: 'Katraj Wonder City', order: 0, etaMinutes: 0, lat: 18.4529, lng: 73.8553, isMajor: true),
        StopModel(stopId: 's302', name: 'Padmavati Chowk', order: 1, etaMinutes: 12, lat: 18.4770, lng: 73.8562, isMajor: false),
        StopModel(stopId: 's303', name: 'Swargate Terminal', order: 2, etaMinutes: 24, lat: 18.5018, lng: 73.8580, isMajor: true),
        StopModel(stopId: 's304', name: 'Dapodi Metro Station', order: 3, etaMinutes: 45, lat: 18.5837, lng: 73.8315, isMajor: true),
        StopModel(stopId: 's305', name: 'Pimpri Chowk', order: 4, etaMinutes: 56, lat: 18.6256, lng: 73.8010, isMajor: true),
        StopModel(stopId: 's306', name: 'Chinchwad Station', order: 5, etaMinutes: 65, lat: 18.6348, lng: 73.7885, isMajor: true),
        StopModel(stopId: 's307', name: 'Nigdi Bhakti Shakti', order: 6, etaMinutes: 75, lat: 18.6570, lng: 73.7667, isMajor: true),
      ],
    ),
  ];

  static final List<BusModel> buses = [
    BusModel(
      busId: 'bus_MH12_AB1234',
      busNumber: 'MH 12 AB 1234',
      routeId: 'route_101',
      routeName: 'Swargate to Hinjawadi IT Park',
      routeNumber: '101-EXP',
      driverId: 'user_driver_1',
      driverName: 'Rajesh Patil',
      conductorId: 'user_conductor_1',
      conductorName: 'Anita Deshmukh',
      capacity: 50,
      currentLoad: 68,
      currentPassengers: 34,
      status: 'on_time',
      currentSpeed: 38,
      nextStop: 'Pune University Circle',
      etaNextStopMin: 4,
      latitude: 18.5410,
      longitude: 73.8340,
      lastUpdated: DateTime.now().toIso8601String(),
      delayMinutes: 0,
    ),
    BusModel(
      busId: 'bus_MH12_CD5678',
      busNumber: 'MH 12 CD 5678',
      routeId: 'route_101',
      routeName: 'Swargate to Hinjawadi IT Park',
      routeNumber: '101-EXP',
      driverId: 'user_driver_2',
      driverName: 'Vijay Shinde',
      conductorId: 'user_conductor_2',
      conductorName: 'Sunita Rao',
      capacity: 50,
      currentLoad: 92,
      currentPassengers: 46,
      status: 'delayed',
      currentSpeed: 14,
      nextStop: 'Wakad Bridge',
      etaNextStopMin: 12,
      latitude: 18.5720,
      longitude: 73.7910,
      lastUpdated: DateTime.now().toIso8601String(),
      delayMinutes: 14,
    ),
    BusModel(
      busId: 'bus_MH12_EF9012',
      busNumber: 'MH 12 EF 9012',
      routeId: 'route_202',
      routeName: 'Pune Station to Hadapsar Gadital',
      routeNumber: '202',
      driverId: 'user_driver_3',
      driverName: 'Mohan Lal',
      conductorId: 'user_conductor_3',
      conductorName: 'Deepak More',
      capacity: 45,
      currentLoad: 40,
      currentPassengers: 18,
      status: 'on_time',
      currentSpeed: 42,
      nextStop: 'Bund Garden',
      etaNextStopMin: 3,
      latitude: 18.5350,
      longitude: 73.8840,
      lastUpdated: DateTime.now().toIso8601String(),
      delayMinutes: 0,
    ),
    BusModel(
      busId: 'bus_MH12_GH3456',
      busNumber: 'MH 12 GH 3456',
      routeId: 'route_303',
      routeName: 'Katraj to Nigdi Pradhikaran',
      routeNumber: '303-BRT',
      driverId: 'user_driver_4',
      driverName: 'Anand Tambe',
      conductorId: 'user_conductor_4',
      conductorName: 'Prakash Gaikwad',
      capacity: 60,
      currentLoad: 75,
      currentPassengers: 45,
      status: 'on_time',
      currentSpeed: 48,
      nextStop: 'Dapodi Metro Station',
      etaNextStopMin: 6,
      latitude: 18.5700,
      longitude: 73.8400,
      lastUpdated: DateTime.now().toIso8601String(),
      delayMinutes: 0,
    ),
  ];

  static final List<TripModel> trips = [
    TripModel(
      tripId: 'trip_101_01',
      routeId: 'route_101',
      routeName: 'Swargate to Hinjawadi IT Park',
      routeNumber: '101-EXP',
      busId: 'bus_MH12_AB1234',
      busNumber: 'MH 12 AB 1234',
      conductorId: 'user_conductor_1',
      conductorName: 'Anita Deshmukh',
      driverId: 'user_driver_1',
      driverName: 'Rajesh Patil',
      ticketCount: 42,
      passengerLoad: 68,
      capacity: 50,
      currentPassengers: 34,
      status: 'in_progress',
      startTime: '08:30 AM',
      timestamp: DateTime.now().toIso8601String(),
      currentStopIndex: 2,
      currentStopName: 'Shivajinagar Bus Station',
      nextStopName: 'Pune University Circle',
      direction: 'UP',
      totalRevenue: 1260.0,
      delayMinutes: 0,
    ),
    TripModel(
      tripId: 'trip_202_01',
      routeId: 'route_202',
      routeName: 'Pune Station to Hadapsar Gadital',
      routeNumber: '202',
      busId: 'bus_MH12_EF9012',
      busNumber: 'MH 12 EF 9012',
      conductorId: 'user_conductor_3',
      conductorName: 'Deepak More',
      driverId: 'user_driver_3',
      driverName: 'Mohan Lal',
      ticketCount: 28,
      passengerLoad: 40,
      capacity: 45,
      currentPassengers: 18,
      status: 'in_progress',
      startTime: '09:00 AM',
      timestamp: DateTime.now().toIso8601String(),
      currentStopIndex: 1,
      currentStopName: 'Ruby Hall Clinic',
      nextStopName: 'Bund Garden',
      direction: 'UP',
      totalRevenue: 720.0,
      delayMinutes: 0,
    ),
  ];

  static final List<TicketModel> tickets = [
    TicketModel(
      ticketId: 'RS-849201',
      tripId: 'trip_101_01',
      routeId: 'route_101',
      routeName: 'Swargate to Hinjawadi IT Park',
      routeNumber: '101-EXP',
      busNumber: 'MH 12 AB 1234',
      passengerId: 'user_passenger_1',
      passengerName: 'Pooja Kulkarni',
      fromStop: 'Swargate Terminal',
      toStop: 'Pune University Circle',
      passengerCount: 1,
      fare: 25.0,
      totalFare: 25.0,
      paymentType: 'razorpay_digital',
      paymentStatus: 'paid',
      timestamp: DateTime.now().subtract(const Duration(minutes: 25)).toIso8601String(),
      qrCodeData: 'RS-TKT-849201|101-EXP|Swargate-Pune Univ|1PAX|₹25',
      conductorId: 'user_conductor_1',
      conductorName: 'Anita Deshmukh',
      issuedByRole: 'conductor',
    ),
    TicketModel(
      ticketId: 'RS-849202',
      tripId: 'trip_101_01',
      routeId: 'route_101',
      routeName: 'Swargate to Hinjawadi IT Park',
      routeNumber: '101-EXP',
      busNumber: 'MH 12 AB 1234',
      fromStop: 'Deccan Gymkhana',
      toStop: 'Hinjawadi Shivaji Chowk',
      passengerCount: 2,
      fare: 35.0,
      totalFare: 70.0,
      paymentType: 'cash',
      paymentStatus: 'paid',
      timestamp: DateTime.now().subtract(const Duration(minutes: 18)).toIso8601String(),
      qrCodeData: 'RS-TKT-849202|101-EXP|Deccan-Hinjawadi|2PAX|₹70',
      conductorId: 'user_conductor_1',
      conductorName: 'Anita Deshmukh',
      issuedByRole: 'conductor',
    ),
    TicketModel(
      ticketId: 'RS-849203',
      tripId: 'trip_101_01',
      routeId: 'route_101',
      routeName: 'Swargate to Hinjawadi IT Park',
      routeNumber: '101-EXP',
      busNumber: 'MH 12 AB 1234',
      fromStop: 'Shivajinagar Bus Station',
      toStop: 'Aundh Gaon',
      passengerCount: 1,
      fare: 20.0,
      totalFare: 20.0,
      paymentType: 'cash',
      paymentStatus: 'paid',
      timestamp: DateTime.now().subtract(const Duration(minutes: 8)).toIso8601String(),
      qrCodeData: 'RS-TKT-849203|101-EXP|Shivajinagar-Aundh|1PAX|₹20',
      conductorId: 'user_conductor_1',
      conductorName: 'Anita Deshmukh',
      issuedByRole: 'conductor',
    ),
  ];

  static final List<IncidentModel> incidents = [
    IncidentModel(
      incidentId: 'inc_101_01',
      routeId: 'route_101',
      routeName: 'Swargate to Hinjawadi IT Park',
      routeNumber: '101-EXP',
      busId: 'bus_MH12_CD5678',
      busNumber: 'MH 12 CD 5678',
      driverId: 'user_driver_2',
      driverName: 'Vijay Shinde',
      type: 'delay',
      description: 'Heavy congestion due to flyover construction work near Wakad Bridge.',
      severity: 'medium',
      status: 'open',
      delayMinutes: 14,
      locationName: 'Wakad Bridge junction',
      lat: 18.5987,
      lng: 73.7634,
      timestamp: DateTime.now().subtract(const Duration(minutes: 20)).toIso8601String(),
    ),
    IncidentModel(
      incidentId: 'inc_101_02',
      routeId: 'route_101',
      routeName: 'Swargate to Hinjawadi IT Park',
      routeNumber: '101-EXP',
      busId: 'bus_MH12_XY7788',
      busNumber: 'MH 12 XY 7788',
      driverId: 'user_driver_5',
      driverName: 'Kishore B',
      type: 'breakdown',
      description: 'Air pressure brake leak warning triggered; vehicle safely pulled to curb.',
      severity: 'critical',
      status: 'resolved',
      delayMinutes: 35,
      locationName: 'Aundh Gaon bus stop',
      lat: 18.5601,
      lng: 73.8066,
      timestamp: DateTime.now().subtract(const Duration(hours: 3)).toIso8601String(),
      resolvedAt: DateTime.now().subtract(const Duration(hours: 2)).toIso8601String(),
      resolutionNotes: 'Depot mobile recovery team arrived and replaced air line fitting.',
    ),
  ];

  static final List<NotificationModel> notifications = [
    NotificationModel(
      id: 'notif_001',
      title: 'Operational Delay Alert: Route 101-EXP',
      message: 'Bus MH 12 CD 5678 is delayed by ~14 mins at Wakad Bridge due to construction congestion.',
      type: 'delay',
      severity: 'warning',
      timestamp: DateTime.now().subtract(const Duration(minutes: 18)).toIso8601String(),
      read: false,
      targetRoles: ['operations_manager', 'driver', 'conductor', 'passenger'],
      routeId: 'route_101',
    ),
    NotificationModel(
      id: 'notif_002',
      title: 'Digital Ticket Verified',
      message: 'Ticket #RS-849201 verified on Bus MH 12 AB 1234 (1 Pax • ₹25).',
      type: 'ticket',
      severity: 'success',
      timestamp: DateTime.now().subtract(const Duration(minutes: 25)).toIso8601String(),
      read: true,
      targetRoles: ['conductor', 'operations_manager'],
      routeId: 'route_101',
    ),
    NotificationModel(
      id: 'notif_003',
      title: 'Breakdown Resolved on Corridor 101',
      message: 'Bus MH 12 XY 7788 maintenance check completed. Restored to service pool.',
      type: 'breakdown',
      severity: 'info',
      timestamp: DateTime.now().subtract(const Duration(hours: 2)).toIso8601String(),
      read: true,
      targetRoles: ['operations_manager', 'driver'],
      routeId: 'route_101',
    ),
  ];

  static final List<RecurringIssueModel> recurringIssues = [
    RecurringIssueModel(
      id: 'rec_101_wakad',
      routeId: 'route_101',
      routeName: 'Swargate to Hinjawadi IT Park',
      routeNumber: '101-EXP',
      incidentCount: 5,
      period: '7_days',
      mostCommonType: 'delay',
      peakProblemPeriod: '5:30 PM – 7:30 PM',
      lastIncidentTime: DateTime.now().subtract(const Duration(minutes: 20)).toIso8601String(),
      recommendation: 'Recurring bottleneck at Wakad Bridge. Suggest increasing scheduled headway buffer by +8 minutes or deploying 1 extra peak-hour shuttle.',
      confidenceScore: 92,
      affectedStops: ['Aundh Gaon', 'Wakad Bridge', 'Hinjawadi Shivaji Chowk'],
    ),
    RecurringIssueModel(
      id: 'rec_202_yerwada',
      routeId: 'route_202',
      routeName: 'Pune Station to Hadapsar Gadital',
      routeNumber: '202',
      incidentCount: 3,
      period: '7_days',
      mostCommonType: 'delay',
      peakProblemPeriod: '8:45 AM – 10:15 AM',
      lastIncidentTime: DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
      recommendation: 'Signal cycle queuing near Yerwada Post Office. Coordinate with traffic division for extended bus-priority green phase.',
      confidenceScore: 84,
      affectedStops: ['Ruby Hall Clinic', 'Bund Garden', 'Yerwada Post Office'],
    ),
  ];
}
